language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install nose pylint
# command to run tests
script:
  - nosetests
#  - find . -name "*.py" -exec pylint -E --disable=import-error '{}' +
branches:
  only:
  - master
  - development
